version: '3.7'

services: 
    shh_docker_python37:
        build: .
        container_name: test_rig
        ports: 
            - "5252:22"
        volumes: 
            - ${HOME}:/home/:rw
        restart: unless-stopped