version: '3.7'

volumes:
  postgres_db:
  pgadmin:

networks:
  postgres_db:
    driver: bridge

# volumes:
#   database_data:
#     driver: local

services:
  postgres_db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_container_local
    volumes:
      - /home/sidkas/docker-apps/volumes/postgres-data:/var/lib/postgresql/data/:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cit_digi}
      PGDATA: /data/postgres
      POSTGRES_DB: postgres_db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    ports:
      - 15432:80
    environment:
      - GUNICORN_THREADS=10
      - PGADMIN_DEFAULT_EMAIL=siddhartha.kasaraneni@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=cit_digi
    volumes:
       - pgadmin:/root/.pgadmin
    depends_on:
      - postgres_db
    networks:
      - postgres_db
    restart: unless-stopped


 