
@startuml 
title Microservice Architechture
package Server <<frame>> {
        package "Data Acquisition (da)" <<storage>> {
        object ZeroMQServer_da {
            ip:localhost
            port:5656
        }
    }

    package "Material Detection (md)" <<storage>> {
        object ZeroMQServer_md {
            ip:localhost
            port:6767
        }
        object ZeroMQClient_md
        ZeroMQServer_md -> ZeroMQClient_md
        ZeroMQClient_md ..> ZeroMQServer_da 
    }

    package "Automatic Control (ac)" <<storage>> {
        object ZeroMQServer_ac {
            ip:localhost
            port:8989
        }
        object ZeroMQClient_ac
        ZeroMQServer_ac -> ZeroMQClient_ac
        ZeroMQClient_ac ..> ZeroMQServer_da 
        ZeroMQClient_ac ..> ZeroMQServer_md
    }
}


package "Android App (app)" <<cloud>> {
    object ZeroMQClient_app
    ZeroMQClient_app ..> ZeroMQServer_da 
    ZeroMQClient_app ..> ZeroMQServer_md
    ZeroMQClient_app ..> ZeroMQServer_ac
}
@enduml
